name: Build and Deploy to ACR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build . -t appstudy.azurecr.io/appstudy:latest

      - name: Push Docker image to ACR
        run: |
          docker push appstudy.azurecr.io/appstudy:latest
